### PR TITLE
fix content-range for 1 result

### PR DESCRIPTION
**Pull request by L-Luciano**
https://stackoverflow.com/questions/15181364/empty-collection-and-http-headers-content-range
fix the result for 0 result and for 1 result

0 result = */0
1 result = 0-0/1

### CODE REVIEW

**Comment by L-Luciano** [comment]
Fix issue : #78

**Review by ccoeurderoy — CHANGES_REQUESTED** [review]
Thank you @L-Luciano for your contribution 👍 It looks good to me!

Could you add a test in order to check the 1-doc case please?

**Comment by L-Luciano** [comment]
yes of course, it's done.

**Review by ccoeurderoy — APPROVED** [review]
Thank you!

**Pull request merged**
